site_name: Roocs
nav:
  - Home: index.md
  - About: about.md
  - Overview: overview.md
  - Dashboard:
    - 2025: dashboard/dashboard-2025.md 
    - 2024: dashboard/dashboard-2024.md
    - 2021-2023: dashboard/dashboard.md
  - Releases: releases.md
  - Contact: contact.md 
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
markdown_extensions:
  - attr_list
plugins:
  - search


