site_name: Roocs
nav:
  - Home: index.md
  - About: about.md
  - Overview: overview.md
  - Dashboard: dashboard.md
  - Releases: releases.md
  - Contact: contact.md 
theme:
  name: material
  logo: images/roocs.svg
  favicon: images/favicon.ico
plugins:
  - search


